add ignored keyword filtering
netlify/twickr pull request #2
Opened 2017-05-04 21:33 UTC by erquhart

It compiles, but I didn't create and test binaries. Hopefully a go dev can approve without running it.

2017-05-04 21:36 UTC, calavera requested changes

2017-05-04 21:36 UTC, calavera commented on main.go
> +					return
don't return here, use `break`. I'm pretty sure we want to keep looping.

2017-05-04 21:37 UTC, calavera commented on config.example.json
> +  "keywordsIgnored": "keywords,you do not want,to track"
json supports lists of strings, why don't we use them rather than splitting this string every time?

2017-05-04 22:47 UTC, erquhart commented on config.example.json
> +  "keywordsIgnored": "keywords,you do not want,to track"
Yeah that makes sense.

2017-05-04 22:49 UTC, erquhart commented on main.go
> +					return
This decodes an individual tweet, so we want to stop if that tweet has an ignored keyword, right?

2017-05-04 22:56 UTC, calavera commented on main.go
> +					return
I meant `continue`, not `break`, sorry for the confusion

2017-05-04 22:56 UTC, verythorough commented on config.example.json
> +  "keywordsIgnored": "keywords,you do not want,to track"
This is silly and small, but the typo in line 8's "your want" actually did make it harder for me to understand until I read line 9's "you do not want"

2017-05-04 22:58 UTC, calavera commented on main.go
> +					return
you want to continue the outer loop, this function decodes all tweets coming from the connection. `Next` is a live streaming feed waiting for messages.

2017-05-04 23:11 UTC, erquhart commented on config.example.json
> +  "keywordsIgnored": "keywords,you do not want,to track"
I'll correct that.

@calavera I remembered why I did this - we're not touching the keywords string (it's consumed by Twitter's api), and I didn't want to have two different signatures for `keywords` and `keywordsIgnored`. The related code is almost negligible in size.

2017-05-05 00:30 UTC, calavera commented on config.example.json
> +  "keywordsIgnored": "keywords,you do not want,to track"
ok

2017-05-05 03:41 UTC, erquhart commented
Adding this comment from mobile - this probably doesn't allow the config to not have the keywordsIgnore field. I'll update in the am.

2017-05-05 14:52 UTC, erquhart commented
@calavera tested live, good to go.

2017-05-05 17:27 UTC, calavera approved these changes

2017-05-05 17:27 UTC, merged